all:
- nvim
- zsh
- tmux
version: 3
items:
  nvchad:
    after:
      - nvim +'hi NormalFloat guibg=#1e222a' +PackerSync
    before:
      - git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1
    files:
      ~/.config/nvim/lua/custom: nvchad
  nvim:
    after:
      - git clone --depth 1 https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim
      - nvim +"PackerSync" +qa
    files:
      ~/.config/nvim/init.lua: nvim-init.lua
      ~/.config/nvim/lua: nvim-lua
  tmux:
    before:
      - git clone https://github.com/gpakosz/.tmux.git ~/.tmux
      - ln -s -f .tmux/.tmux.conf $HOME/.tmux.conf
    files:
      ~/.tmux.conf.local: tmux.conf.local
  vim:
    files:
      ~/.vimrc: vimrc
      ~/.vimrc.d: vimrc.d
  zsh:
    before:
      - wget -O $HOME/antigen.zsh git.io/antigen
    files:
      ~/.zshrc: zshrc

