alias gauth="gcloud auth application-default login";
alias ls="eza";
alias ll="eza -l";
alias la="eza -la";
alias lg="lazygit";
alias oc="opencode";
alias e="$EDITOR";
alias zl="zellij";
alias cat="bat";
